package com.telapp.auro.persist.entities;

// Generated 8 Mar, 2015 9:42:55 PM by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * AuroSlotStatistics generated by hbm2java
 */
@Entity
@Table(name = "auro_slot_statistics", catalog = "telapp_auro", uniqueConstraints = @UniqueConstraint(columnNames = "device_id"))
public class AuroSlotStatistics implements java.io.Serializable {

	private Integer idauroSlotStatistics;
	private AuroDeviceReg auroDeviceReg;
	private Integer slotStatus;
	private Date upatedTime;

	public AuroSlotStatistics() {
	}

	public AuroSlotStatistics(AuroDeviceReg auroDeviceReg, Integer slotStatus,
			Date upatedTime) {
		this.auroDeviceReg = auroDeviceReg;
		this.slotStatus = slotStatus;
		this.upatedTime = upatedTime;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idauro_slot_statistics", unique = true, nullable = false)
	public Integer getIdauroSlotStatistics() {
		return this.idauroSlotStatistics;
	}

	public void setIdauroSlotStatistics(Integer idauroSlotStatistics) {
		this.idauroSlotStatistics = idauroSlotStatistics;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "device_id", unique = true)
	public AuroDeviceReg getAuroDeviceReg() {
		return this.auroDeviceReg;
	}

	public void setAuroDeviceReg(AuroDeviceReg auroDeviceReg) {
		this.auroDeviceReg = auroDeviceReg;
	}

	@Column(name = "slot_status")
	public Integer getSlotStatus() {
		return this.slotStatus;
	}

	public void setSlotStatus(Integer slotStatus) {
		this.slotStatus = slotStatus;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "upated_time", length = 19)
	public Date getUpatedTime() {
		return this.upatedTime;
	}

	public void setUpatedTime(Date upatedTime) {
		this.upatedTime = upatedTime;
	}

}
