package com.telapp.auro.persist.entities;

// Generated 8 Mar, 2015 9:42:55 PM by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * AuroLogTable generated by hbm2java
 */
@Entity
@Table(name = "Auro_log_table")
public class AuroLogTable implements java.io.Serializable {

	private Integer auroLogId;
	private String deviceName;
	private String deviceMacId;
	private String slotname;
	private Integer slotstatus;
	private Date createdTime;

	public AuroLogTable() {
	}

	public AuroLogTable(String deviceName, String deviceMacId, String slotname,
			Integer slotstatus, Date createdTime) {
		this.deviceName = deviceName;
		this.deviceMacId = deviceMacId;
		this.slotname = slotname;
		this.slotstatus = slotstatus;
		this.createdTime = createdTime;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "auro_log_id", unique = true, nullable = false)
	public Integer getAuroLogId() {
		return this.auroLogId;
	}

	public void setAuroLogId(Integer auroLogId) {
		this.auroLogId = auroLogId;
	}

	@Column(name = "device_name", length = 45)
	public String getDeviceName() {
		return this.deviceName;
	}

	public void setDeviceName(String deviceName) {
		this.deviceName = deviceName;
	}

	@Column(name = "device_mac_id", length = 250)
	public String getDeviceMacId() {
		return this.deviceMacId;
	}

	public void setDeviceMacId(String deviceMacId) {
		this.deviceMacId = deviceMacId;
	}

	@Column(name = "slotname", length = 45)
	public String getSlotname() {
		return this.slotname;
	}

	public void setSlotname(String slotname) {
		this.slotname = slotname;
	}

	@Column(name = "slotstatus")
	public Integer getSlotstatus() {
		return this.slotstatus;
	}

	public void setSlotstatus(Integer slotstatus) {
		this.slotstatus = slotstatus;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_time", length = 19)
	public Date getCreatedTime() {
		return this.createdTime;
	}

	public void setCreatedTime(Date createdTime) {
		this.createdTime = createdTime;
	}

}
